bsub < ./Combined_Bladder_mm10_MIE.sh
bsub < ./Combined_Kidney_mm10_MIE.sh
bsub < ./Combined_LimbMuscle_mm10_MIE.sh
bsub < ./Combined_Liver_mm10_MIE.sh
bsub < ./Combined_Lung_mm10_MIE.sh
bsub < ./Combined_MammaryGland_mm10_MIE.sh
bsub < ./Combined_Marrow_mm10_MIE.sh
bsub < ./Combined_Spleen_mm10_MIE.sh
bsub < ./Combined_Tongue_mm10_MIE.sh
bsub < ./Combined_Trachea_mm10_MIE.sh
bsub < ./Combined_HeartandAorta_mm10_MIE.sh
bsub < ./Combined_Thymus_mm10_MIE.sh
bsub < ./Combined_Total_mm10_MIE.sh
